"""initial schema

Revision ID: 3831b9b9fceb
Revises: 
Create Date: 2026-04-28 20:38:58.129016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3831b9b9fceb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('auth_source', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('theme', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("auth_source IN ('local','ldap')", name='ck_users_auth_source'),
    sa.CheckConstraint("role IN ('admin','operator')", name='ck_users_role'),
    sa.CheckConstraint("theme IN ('system','light','dark')", name='ck_users_theme'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('path_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('path_entries', schema=None) as batch_op:
        batch_op.create_index('ix_path_entries_path', ['path'], unique=False)

    op.create_table('rotation_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_entry_id', sa.Integer(), nullable=False),
    sa.Column('operator_user_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('encrypted_count', sa.Integer(), nullable=True),
    sa.Column('plain_count', sa.Integer(), nullable=True),
    sa.Column('new_file_count', sa.Integer(), nullable=True),
    sa.Column('grew_count', sa.Integer(), nullable=True),
    sa.Column('shrunk_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running','completed','failed')", name='ck_scans_status'),
    sa.ForeignKeyConstraint(['operator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['path_entry_id'], ['path_entries.id'], ),
    sa.ForeignKeyConstraint(['scheduled_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index('ix_scans_path_completed', ['path_entry_id', 'completed_at'], unique=False)

    op.create_table('file_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mtime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_encrypted_named', sa.Boolean(), nullable=False),
    sa.Column('prev_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('size_delta_bytes', sa.BigInteger(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshots_scan', ['scan_id'], unique=False)
        batch_op.create_index('ix_snapshots_scan_relpath', ['scan_id', 'relative_path'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_scan_relpath')
        batch_op.drop_index('ix_snapshots_scan')

    op.drop_table('file_snapshots')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index('ix_scans_path_completed')

    op.drop_table('scans')
    op.drop_table('settings')
    op.drop_table('rotation_assignments')
    with op.batch_alter_table('path_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_path_entries_path')

    op.drop_table('path_entries')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))

    op.drop_table('audit_log')
    op.drop_table('users')
    # ### end Alembic commands ###
