"""v2.0.2 add scan.is_hidden, workstation, user_agent

Revision ID: b80b11b67b16
Revises: 3831b9b9fceb
Create Date: 2026-04-29 03:51:17.843996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80b11b67b16'
down_revision = '3831b9b9fceb'
branch_labels = None
depends_on = None


def upgrade():
    # is_hidden gets a server_default so existing rows backfill to FALSE.
    # workstation and user_agent are nullable and need no backfill.
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'is_hidden', sa.Boolean(), nullable=False,
            server_default=sa.false(),
        ))
        batch_op.add_column(sa.Column('workstation', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_column('user_agent')
        batch_op.drop_column('workstation')
        batch_op.drop_column('is_hidden')

    # ### end Alembic commands ###
